// <auto-generated />
using BFT21_Endprojekt_Finanzmanager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BFT21_Endprojekt_Finanzmanager.Migrations
{
    [DbContext(typeof(DatabaseDefiner))]
    [Migration("20240201113701_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.KapitalUnterteilungsGruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Betrag")
                        .HasColumnType("REAL");

                    b.Property<int>("Einct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eineuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Einhuderteuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuenfct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuenfeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuenfzigct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuenfzigeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zehnct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zehneuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zwanzigct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zwanzigeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zweict")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zweieuro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KontoId");

                    b.ToTable("kapitalUnterteilungsGruppen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnzeigeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bankleitzahl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InhaberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KontoTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kontoname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kontonummer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kontostand")
                        .HasColumnType("REAL");

                    b.Property<string>("Laendercode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pruefsumme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WaerungsTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InhaberId");

                    b.ToTable("Konten");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.KapitalUnterteilungsGruppe", b =>
                {
                    b.HasOne("BFT21_Endprojekt_Finanzmanager.Database.Konto", "Konto")
                        .WithMany("KapitalUnterteilungsGruppen")
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konto");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.HasOne("BFT21_Endprojekt_Finanzmanager.Database.Person", "Inhaber")
                        .WithMany("Konten")
                        .HasForeignKey("InhaberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inhaber");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.Navigation("KapitalUnterteilungsGruppen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Person", b =>
                {
                    b.Navigation("Konten");
                });
#pragma warning restore 612, 618
        }
    }
}
