// <auto-generated />
using BFT21_Endprojekt_Finanzmanager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BFT21_Endprojekt_Finanzmanager.Migrations
{
    [DbContext(typeof(DatabaseDefiner))]
    partial class DatabaseDefinerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.KapitalUnterteilungsGruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("betrag")
                        .HasColumnType("REAL");

                    b.Property<int>("einct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("eineuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("einhuderteuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fuenfct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fuenfeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fuenfzigct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fuenfzigeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kontoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zehnct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zehneuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zwanzigct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zwanzigeuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zweict")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zweieuro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("kontoId");

                    b.ToTable("kapitalUnterteilungsGruppen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("anzeigeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("bankleitzahl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("inhaberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kontoTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kontoname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("kontonummer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("kontostand")
                        .HasColumnType("REAL");

                    b.Property<string>("laendercode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lagerort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pruefsumme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("waerungsTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("walletAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("webAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("inhaberId");

                    b.ToTable("Konten");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.KapitalUnterteilungsGruppe", b =>
                {
                    b.HasOne("BFT21_Endprojekt_Finanzmanager.Database.Konto", "konto")
                        .WithMany("KapitalUnterteilungsGruppen")
                        .HasForeignKey("kontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("konto");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.HasOne("BFT21_Endprojekt_Finanzmanager.Database.Person", "inhaber")
                        .WithMany("konten")
                        .HasForeignKey("inhaberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inhaber");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Konto", b =>
                {
                    b.Navigation("KapitalUnterteilungsGruppen");
                });

            modelBuilder.Entity("BFT21_Endprojekt_Finanzmanager.Database.Person", b =>
                {
                    b.Navigation("konten");
                });
#pragma warning restore 612, 618
        }
    }
}
